Depositos/urls.py
from django.conf.urls import url, patterns

from .views import *

urlpatterns = patterns('',
    url(r'^$', Index.as_view(), name = 'Index'),
    url(r'^listar/(?P<pk>\d+)/$', DepositosListar.as_view(), name = 'Listar'),
    url(r'^formulario/(?P<action>.*)$', departmentAction, name='Accion'),

    # Exportar a CSV
    url(r'^exportarCSV/$', DepositoCSV, 'exportarCSV'),

    url(r'^prueba/$', Prueba.as_view())
)

SIAD/urls.py
# -*- coding: utf-8 -*-
from pickle import PUT
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers
from Instancias.views import DistritoViewSet, SedeViewSet, InstanciaViewSet
from WebServices.views import *

router = routers.DefaultRouter()
router.register(r'ws/Distritos', DistritoViewSet)
router.register(r'ws/Sedes', SedeViewSet)
router.register(r'ws/Instancias', InstanciaViewSet)

router.register(r'WS/Distrito/Arbol', Distrito, base_name = 'ArbolDistrito')
router.register(r'WS/Sede/Arbol', Sede, base_name = 'ArbolSede')
router.register(r'WS/Juzgado/Arbol', Juzgado, base_name = 'ArbolJuzgado')

# WS/Depositos/Juzgado/1
router.register(r'WS/Depositos/Juzgado', DepositosListar, base_name = 'DepositoListar')
#url(r'^sede/(?P<pk>\d+)/$', SedeListar.as_view(), name = 'Sede'),


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SIAD.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^instancias/', include('Instancias.urls', namespace = 'Instancias')),
    url(r'^ws/', include('WebServices.urls', namespace = 'WS')),


    #
    # SERIALIZERS
    # Enlazando nuestra API usando el ruteo automático de URL's
    url(r'^', include(router.urls)),

    # Incluyendo las URL's para la API navegable
    url(r'^api-auth/', include('rest_framework.urls', namespace = 'rest_framework')),
    #url(r'insta')

    #
    # DEPÓSITOS
    #
    url(r'^depositos/', include('Depositos.urls', namespace = 'Depositos')),
)

SIAD/templates/siad/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es-pe">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>
            {% block Titulo %}
                Elio Clímaco
            {% endblock Titulo %}
        </title>



        <!-- Pie de página -->
        <link href="{% static 'inventarios/css/sticky-footer.css' %}" rel="stylesheet">

        <!-- Initializr -->
        <link href="{% static 'inventarios/css/main.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'inventarios/js/vendor/modernizr-2.6.2.min.js' %}" type="text/javascript"></script>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- DataTables -->
        <link href="{% static 'inventarios/css/jquery.dataTables-1.10.1.css' %}" rel="stylesheet" type="text/css">
        <script src="{% static 'inventarios/js/jquery-1.11.1.js' %}" type="application/javascript" language="JavaScript"></script>
        <script src="{% static 'inventarios/js/jquery.dataTables-1.10.1.js' %}" type="application/javascript" language="JavaScript"></script>
        {% block Scripts %}
        {% endblock Scripts %}
        <!--/DataTables -->

        <!-- Bootstrap -->
        <link href="{% static 'inventarios/css/bootstrap-3.2.0.css' %}" rel="stylesheet">
        <script src="{% static 'inventarios/js/bootstrap-3.2.0.js' %}" type="application/javascript" language="JavaScript"></script>
    </head>

    <body>           
        <!-- Barra -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container-fluid"><!-- Contenedor -->
                <div class="navbar-header"><!-- Agrupa Brand y Toggle -->

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#idBarraPrincipal"><!-- Toggle -->
                        <span class="sr-only">Navegación alternativa</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button><!-- /Toggle -->

                    <!-- Brand -->
                    <a class="navbar-brand" href="#"><img src="{% static 'inventarios/img/LogoPJ_01.png' %}"> Poder Judicial</a>
                </div><!-- /Agrupa Brand y Toggle -->

                <!-- Barra: Items -->
                <div class="collapse navbar-collapse" id="idBarraPrincipal">
                    <ul class="nav navbar-nav">                        
                        <li><a href="{% url 'Depositos:Listar' %}"><span class="glyphicon glyphicon-cog"></span> Depósitos</a></li>
                        <!-- Barra: Dropdown -->
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-print"></span> Equipos <b class="caret"></b></a>
                            
                            <ul class="dropdown-menu">
                                <li><a href="#">Asignados</a></li>
                                <li><a href="#">Historial</a></li>
                                <li><a href="#">Pecosas</a></li>

                                <li class="divider"></li>

                                <li><a href="#">Reportes</a></li>
                            </ul>
                        </li>
                        <!-- /Barra: Dropdown -->
                    </ul>

                    <!-- Barra Items Derecha -->
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> Elio Clímaco <b class="caret"></b></a>

                            <ul class="dropdown-menu">
                                <li><a href="#">Datos de Usuario</a></li>                                
                                <li><a href="#">Cambiar contraseña</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Cerrar cesión</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /Barra: Items -->
            </div><!-- /Contenedor -->
        </nav>     
        <!-- /Barra -->

        {% block Contenido %}
        {% endblock Contenido %}

        <!-- Footer -->
        <div id="footer">
            <div class="container">
                <p class="text-muted colortexto" >
                    Área: Juzgado Penal de Investigación Preparatoria
                </p>
            </div>
        </div>
        <!-- /Footer -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
{#        <script src="{% static 'inventarios/js/jquery.min.js' %}"></script>#}
        <!-- Include all compiled plugins (below), or include individual files as needed -->
{#        <script src="{% static 'inventarios/js/bootstrap.min.js' %}"></script>#}
        <script src="{% static 'inventarios/js/main.js' %}"></script>
    </body>
</html>